version:  '3.8'

services:
  # mysql
  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wasim
      MYSQL_DATABASE: hospital
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build:
      context: ./Doctor-Patient-Portal
      dockerfile: Dockerfile
    container_name: hospital_app
    restart: always
    ports:
      - "8000:8080"
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql+pymysql://root:wasim@db/hospital

volumes:
  db_data:
    driver: local